### ISSUE TITLE
Crash during starting dfu

### ISSUE THREAD

**Issue by klakling** [Laerdal/Laerdal.Xamarin.Dfu.Android#1]
**Describe the bug**
Crash during starting dfu
May be the gosn jar is not included in project?

**Screenshots**
![screenshot 102](https://user-images.githubusercontent.com/13247193/102210032-02df8c00-3f15-11eb-8a94-169a4323932f.jpg)

**Smartphone (please complete the following information):**
 - Device: [Moto G8]
 - OS: [Android 10]

**Additional context**
Is the same issue?
https://github.com/NordicSemiconductor/Android-DFU-Library/issues/208

**Comment by framinosona** [comment]
Thank you for that bug report,

I've published a new version: [1.11.1.13](https://www.nuget.org/packages/Laerdal.Xamarin.Dfu.Android/1.11.1.13)

Could you try it and let me know?

**Comment by klakling** [comment]
When I upgrade to 1.11.1.13,that' fine.
Thank you solving the issue. @framinosona
